# Add 'core' label to any change to app/ files
core:
- app/**/*

# Add 'component' label to any change to components/ files
component:
- components/**/*

# Add 'documentation' label to any change to markdown files
documentation:
- '**/*.md'

# Add 'configuration' label to any change to configuration files
configuration:
- '**/*.json'
- '**/*.js'
- '**/*.yml'
- '**/*.yaml'

# Add 'public' label to any change to public/ files
public:
- public/**/*

# Add 'styles' label to any change to CSS files
styles:
- '**/*.css'
- '**/*.scss'

# Add 'test' label to any change to test files
test:
- '**/*.test.js'
- '**/*.spec.js'
- '**/*.test.jsx'
- '**/*.spec.jsx'

# Add 'dependencies' label to any change to package.json or yarn.lock
dependencies:
- package.json
- package-lock.json
- yarn.lock

# Add 'github_actions' label to any change to .github/workflows files
github_actions:
- .github/workflows/**/*