[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

# Remove Next.js plugin as we're using static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200