[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

# Remove Next.js plugin as we're using static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# Handle 404s properly for SPA
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200