'use client';

import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service | GitHub Profile README Generator',
  description: 'Terms of service for the GitHub Profile README Generator tool. Learn about the terms governing your use of our service.',
  keywords: 'github readme generator terms, github profile terms of service, readme generator usage terms',
};

export default function TermsOfService() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="mb-8">
        <Button
          variant="ghost"
          size="sm"
          asChild
          className="mb-4"
        >
          <Link href="/" className="flex items-center gap-2">
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
        </Button>
        
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: {new Date().toISOString().split('T')[0]}</p>
      </div>
      
      <div className="space-y-8 text-muted-foreground">
        <section>
          <h2 className="text-xl font-semibold mb-4 text-foreground">1. Introduction</h2>
          <p>
            Welcome to GitHub Profile README Generator. These Terms of Service ("Terms") govern your use of our website
            located at https://github-profile-readme-generator.vercel.app/ ("Service") operated by GitHub Profile README Generator.
            By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms,
            you may not access the Service.
          </p>
        </section>
        
        <section>
          <h2 className="text-xl font-semibold mb-4 text-foreground">2. Use of Service</h2>
          <p className="mb-4">
            The GitHub Profile README Generator is provided as a free service to help users create and customize GitHub profile READMEs.
            When using our Service, you agree to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Use the Service only for lawful purposes and in accordance with these Terms</li>
            <li>Not use the Service in any way that could damage, disable, overburden, or impair the Service</li>
            <li>Not attempt to gain unauthorized access to any part of the Service</li>
            <li>Not use the Service for any commercial purposes without our express consent</li>
          </ul>
        </section>
        
        <section>
          <h2 className="text-xl font-semibold mb-4 text-foreground">3. Intellectual Property</h2>
          <p className="mb-4">
            The Service and its original content, features, and functionality are owned by GitHub Profile README Generator
            and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
          </p>
          <p>
            The README content generated by our Service is owned by you. You are free to use, modify, and distribute the
            generated content as you see fit, subject to GitHub's terms of service for content hosted on their platform.
          </p>
        </section>
        
        <section>
          <h2 className="text-xl font-semibold mb-4 text-foreground">4. User Content</h2>
          <p>
            Our Service allows you to create and customize GitHub profile READMEs. You are solely responsible for the content
            you generate using our Service. You represent and warrant that you own or have the necessary permissions to use
            and authorize us to process any content that you submit through our Service.
          </p>
        </section>
        
        <section>
          <h2 className="text-xl font-semibold mb-4 text-foreground">5. Links to Other Websites</h2>
          <p>
            Our Service may contain links to third-party websites or services that are not owned or controlled by GitHub Profile README Generator.
            We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party
            websites or services. You acknowledge and agree that we shall not be responsible or liable, directly or indirectly,
            for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content,
            goods, or services available on or through any such websites or services.
          </p>
        </section>
        
        <section>
          <h2 className="text-xl font-semibold mb-4 text-foreground">6. Limitation of Liability</h2>
          <p>
            In no event shall GitHub Profile README Generator, nor its directors, employees, partners, agents, suppliers, or affiliates,
            be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation,
            loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability
            to access or use the Service.
          </p>
        </section>
        
        <section>
          <h2 className="text-xl font-semibold mb-4 text-foreground">7. Disclaimer</h2>
          <p>
            Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis.
            The Service is provided without warranties of any kind, whether express or implied, including, but not limited to,
            implied warranties of merchantability, fitness for a particular purpose, non-infringement, or course of performance.
          </p>
        </section>
        
        <section>
          <h2 className="text-xl font-semibold mb-4 text-foreground">8. Changes to Terms</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material,
            we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change
            will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective,
            you agree to be bound by the revised terms.
          </p>
        </section>
        
        <section>
          <h2 className="text-xl font-semibold mb-4 text-foreground">9. Governing Law</h2>
          <p>
            These Terms shall be governed and construed in accordance with the laws, without regard to its conflict of law provisions.
            Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
          </p>
        </section>
        
        <section>
          <h2 className="text-xl font-semibold mb-4 text-foreground">10. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us by creating an issue on our
            <a href="https://github.com/Samarth-Sharma21/Smart-github-profile-readme-generator" className="text-primary hover:underline ml-1" target="_blank" rel="noopener noreferrer">
              GitHub repository
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}