name: Accessibility Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1' # Run once a week at midnight on Monday

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start server
        run: npm run start & npx wait-on http://localhost:3000

      - name: Run accessibility tests
        run: |
          npx pa11y-ci --sitemap http://localhost:3000/sitemap.xml --sitemap-find "https://github-profile-readme-generator.com" --sitemap-replace "http://localhost:3000" --reporter=json > pa11y-results.json

      - name: Upload accessibility results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-report
          path: pa11y-results.json

      - name: Check accessibility results
        run: |
          if [ -s pa11y-results.json ]; then
            echo "Accessibility issues found. See the uploaded report for details."
            exit 1
          else
            echo "No accessibility issues found."
          fi