name: Check Broken Links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 3' # Run once a week at midnight on Wednesday

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start server
        run: npm run start & npx wait-on http://localhost:3000

      - name: Check for broken links
        run: |
          npx broken-link-checker http://localhost:3000 --recursive --ordered --exclude linkedin.com --exclude twitter.com --exclude facebook.com --exclude instagram.com --exclude github.com