name: Generate Changelog

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: conventional-changelog/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'CHANGELOG.md'
          preset: 'angular'
          release-count: 0
          tag-prefix: 'v'
          git-message: 'chore(release): update CHANGELOG.md for ${nextRelease.version} [skip ci]'
          git-user-name: 'github-actions'
          git-user-email: 'github-actions@github.com'

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update CHANGELOG.md [skip ci]'
          file_pattern: CHANGELOG.md
          commit_user_name: 'GitHub Actions'
          commit_user_email: 'github-actions@github.com'
          commit_author: 'GitHub Actions <github-actions@github.com>'