name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Run once a week at midnight on Sunday

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --json > npm-audit.json || true

      - name: Check for high severity vulnerabilities
        run: |
          HIGH_VULNS=$(cat npm-audit.json | jq '.vulnerabilities | map(select(.severity == "high" or .severity == "critical")) | length')
          echo "High severity vulnerabilities found: $HIGH_VULNS"
          if [ "$HIGH_VULNS" -gt 0 ]; then
            echo "Warning: High severity vulnerabilities found. Review npm-audit.json for details."
          fi

      - name: Run Snyk scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Run OWASP ZAP scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Check Content Security Policy
        run: |
          # Start server
          npm run start & npx wait-on http://localhost:3000
          
          # Check for CSP headers
          echo "Checking Content-Security-Policy headers..."
          CSP_HEADER=$(curl -s -I http://localhost:3000 | grep -i "Content-Security-Policy")
          echo "$CSP_HEADER"
          
          if [ -z "$CSP_HEADER" ]; then
            echo "Warning: No Content-Security-Policy header found"
          fi
          
          # Check for other security headers
          echo "\nChecking other security headers..."
          curl -s -I http://localhost:3000 | grep -i "X-Content-Type-Options"
          curl -s -I http://localhost:3000 | grep -i "X-Frame-Options"
          curl -s -I http://localhost:3000 | grep -i "X-XSS-Protection"
          curl -s -I http://localhost:3000 | grep -i "Referrer-Policy"
          curl -s -I http://localhost:3000 | grep -i "Strict-Transport-Security"

      - name: Upload security scan results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-report
          path: |
            npm-audit.json
            snyk-*.json
            zap-*